[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
tokio = { version = "1.43.1", features = ["macros", "rt-multi-thread"] }
